tags:
  - "Tasks"
summary: "Delete a task"
description: "Remove a task owned by the authenticated user."
operationId: "deleteTask"
parameters:
  - name: "task_id"
    in: "path"
    required: true
    type: "string"
    description: "ID of the task to be deleted"
responses:
  200:
    description: "Task deleted successfully"
    schema:
      type: "object"
      properties:
        status:
          type: "string"
          description: "Response status"
        message:
          type: "string"
          description: "Success message"
  404:
    description: "Task not found or not owned by the current user"
